In [1]:
import pandas as pd
import numpy as np

In [13]:
link="https://en.wikipedia.org/wiki/List_of_American_films_of_2020"

In [25]:
df=pd.read_html(link,header=0)

In [26]:
df_f=df[3].append(df[4].append(df[5].append(df[6],ignore_index=True),ignore_index=True),ignore_index=True)

In [27]:
df_f

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,3,The Grudge,Screen Gems / Stage 6 Films / Ghost House Pict...,Nicolas Pesce (director/screenplay); Andrea Ri...,[2]
1,JANUARY,10,Underwater,20th Century Fox / TSG Entertainment / Chernin...,"William Eubank (director); Brian Duffield, Ada...",[3]
2,JANUARY,10,Like a Boss,Paramount Pictures,"Miguel Arteta (director); Sam Pitman, Adam Col...",[4]
3,JANUARY,10,Inherit the Viper,Barry Films / Tycor International Film Company,Anthony Jerjen (director); Andrew Crabtree (sc...,[5]
4,JANUARY,10,The Sonata,Screen Media Films,Andrew Desmond (director/screenplay); Arthur M...,[6]
...,...,...,...,...,...,...
159,DECEMBER,18,Dune,Warner Bros. Pictures / Legendary Entertainment,Denis Villeneuve (director/screenplay); Jon Sp...,[159]
160,DECEMBER,18,West Side Story,20th Century Studios / Amblin Entertainment,Steven Spielberg (director); Tony Kushner (scr...,[3]
161,DECEMBER,18,Coming 2 America,Paramount Pictures,"Craig Brewer (director); Kenya Barris, Barry W...",[160]
162,DECEMBER,23,The Croods 2,Universal Pictures / DreamWorks Animation,"Joel Crawford (director); Kevin Hageman, Dan H...",[161]
163,DECEMBER,25,News of the World,Universal Pictures,Paul Greengrass (director/screenplay); Luke Da...,[162]

In [28]:
from tmdbv3api import TMDb
import json
import requests
tmdb=TMDb()
tmdb.api_key='643b71da3b8e6b8deb2a4171b281bc7d'

In [29]:
from tmdbv3api import Movie
tmdb_movie=Movie()
def get_genre(x):
    genres=[]
    result=tmdb_movie.search(x)
    movie_id=result[0].id
    #print(movie_id)
    response=requests.get('https://api.themoviedb.org/3/movie/{}?api_key=643b71da3b8e6b8deb2a4171b281bc7d'.format(movie_id))
    data_json=response.json()
    #print(data_json)
    if data_json['genres']:
        print(data_json['genres'])
        genre_str=" "
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [32]:
df_f['genres']=df_f['Title'].map(lambda x: get_genre(str(x)))

[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 28, 'name': 'Action'}, {'id': 27, 'name': 'Horror'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 35, 'name': 'Comedy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}, {'id': 80, 'name': 'Crime'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}]
[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'name': 'War'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 16, 'name': 'Animation'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 27, 'name': 'Horror'}, {'id': 14, 'name': 'Fantasy'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 10751, 'name': 'Family'}, {'id': 9648, 'name': 'Mystery'}, {'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}, {'id': 878, 'name': 'Science Fiction'}]
[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 27, 'name': 'Horror'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 35, 'name': 'Comedy'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 27, 'name': 'Horror'}]
[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 28, 'name': 'Action'}]
[{'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}]
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}]
[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'name': 'Music'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 10752, 'name': 'War'}]
[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 27, 'name': 'Horror'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 28, 'name': 'Action'}]
[{'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}, {'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}, {'id': 12, 'name': 'Adventure'}, {'id': 10402, 'name': 'Music'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 10751, 'name': 'Family'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 27, 'name': 'Horror'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10770, 'name': 'TV Movie'}]
[{'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 10751, 'name': 'Family'}, {'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 28, 'name': 'Action'}, {'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}, {'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 10751, 'name': 'Family'}, {'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]
[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 10751, 'name': 'Family'}, {'id': 28, 'name': 'Action'}]
[{'id': 10752, 'name': 'War'}, {'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]
[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]
[{'id': 99, 'name': 'Documentary'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]
[{'id': 10751, 'name': 'Family'}, {'id': 28, 'name': 'Action'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 36, 'name': 'History'}, {'id': 10402, 'name': 'Music'}, {'id': 18, 'name': 'Drama'}]
[{'id': 27, 'name': 'Horror'}, {'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 28, 'name': 'Action'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 10752, 'name': 'War'}, {'id': 28, 'name': 'Action'}, {'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}, {'id': 9648, 'name': 'Mystery'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 53, 'name': 'Thriller'}]
[{'id': 80, 'name': 'Crime'}, {'id': 53, 'name': 'Thriller'}, {'id': 28, 'name': 'Action'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 16, 'name': 'Animation'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]
[{'id': 28, 'name': 'Action'}, {'id': 27, 'name': 'Horror'}, {'id': 878, 'name': 'Science Fiction'}]
[{'id': 10402, 'name': 'Music'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'name': 'War'}]
[{'id': 35, 'name': 'Comedy'}]
[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}]

[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 878, 'name': 'Science Fiction'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 99, 'name': 'Documentary'}]
[{'id': 10751, 'name': 'Family'}, {'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 36, 'name': 'History'}, {'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 27, 'name': 'Horror'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}]
[{'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name': 'Action'}, {'id': 10752, 'name': 'War'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}]
[{'id': 53, 'name': 'Thriller'}]
[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 27, 'name': 'Horror'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}]
[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 10749, 'name': 'Romance'}, {'id': 18, 'name': 'Drama'}]
[{'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}]
[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name': 'History'}]
[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'name': 'Mystery'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 16, 'name': 'Animation'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}, {'id': 878, 'name': 'Science Fiction'}]
[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 27, 'name': 'Horror'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}, {'id': 80, 'name': 'Crime'}]
[{'id': 10751, 'name': 'Family'}, {'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 28, 'name': 'Action'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}, {'id': 12, 'name': 'Adventure'}, {'id': 9648, 'name': 'Mystery'}]
[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}, {'id': 10402, 'name': 'Music'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]
[{'id': 878, 'name': 'Science Fiction'}, {'id': 53, 'name': 'Thriller'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 27, 'name': 'Horror'}]
[{'id': 18, 'name': 'Drama'}]
[{'id': 35, 'name': 'Comedy'}, {'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 12, 'name': 'Adventure'}]
[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]
[{'id': 35, 'name': 'Comedy'}]
[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}]
[{'id': 18, 'name': 'Drama'}, {'id': 37, 'name': 'Western'}]

In [37]:
df_2020=df_f[['Title','Cast and crew','genres']]

In [40]:
df_2020

,Title,Cast and crew,genres
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Action Horror Science Fiction Thriller
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy
3,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Drama Thriller Crime
4,The Sonata,Andrew Desmond (director/screenplay); Arthur M...,Horror Thriller Mystery
...,...,...,...
159,Dune,Denis Villeneuve (director/screenplay); Jon Sp...,Action Science Fiction Adventure
160,West Side Story,Steven Spielberg (director); Tony Kushner (scr...,Crime Drama Romance
161,Coming 2 America,"Craig Brewer (director); Kenya Barris, Barry W...",Comedy
162,The Croods 2,"Joel Crawford (director); Kevin Hageman, Dan H...",Action Adventure Animation Comedy Family Fantasy
163,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama Western

In [38]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [42]:
df_2020['director_name']=df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\pallaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [47]:
df_2020.dtypes

Title            object
Cast and crew    object
genres           object
director_name    object
dtype: object

In [48]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [52]:
df_2020['actor_1_name']=df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

C:\Users\pallaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [54]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", "))<2:
        return np.nan
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [55]:
 df_2020['actor_2_name']=df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\pallaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [56]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", "))<3:
        return np.nan
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [57]:
df_2020['actor_3_name']=df_2020['Cast and crew'].map(lambda x: get_actor3(str(x)))

C:\Users\pallaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [58]:
df_2020=df_2020.rename(columns={'Title':'movie_title'})

In [59]:
new_df20=df_2020.loc[:,['director_name',
       'actor_1_name', 'actor_2_name', 'actor_3_name','genres','movie_title']]

In [60]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Horror Mystery,The Grudge
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,Underwater
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,Like a Boss
3,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama Thriller Crime,Inherit the Viper
4,Andrew Desmond,Freya Tingley,Simon Abkarian,Rutger Hauer,Horror Thriller Mystery,The Sonata
...,...,...,...,...,...,...
159,Denis Villeneuve,TimothÃ©e Chalamet,Rebecca Ferguson,Oscar Isaac,Action Science Fiction Adventure,Dune
160,Steven Spielberg,Ansel Elgort,Rachel Zegler,Ariana DeBose,Crime Drama Romance,West Side Story
161,Craig Brewer,Eddie Murphy,Jermaine Fowler,Arsenio Hall,Comedy,Coming 2 America
162,Joel Crawford,Nicolas Cage,Emma Stone,Ryan Reynolds,Action Adventure Animation Comedy Family Fantasy,The Croods 2
163,Paul Greengrass,Tom Hanks,Helena Zengel,Neil Sandilands,Drama Western,News of the World

In [61]:
new_df20['actor_2_name']=new_df20['actor_2_name'].replace(np.NaN,'unknown')
new_df20['actor_3_name']=new_df20['actor_3_name'].replace(np.NaN,'unknown')

In [62]:
new_df20['movie_title']=new_df20['movie_title'].str.lower()

In [64]:
new_df20['comb']=new_df20['actor_1_name'] +' '+ new_df20['actor_2_name'] +' '+ new_df20['actor_3_name'] +' '+ new_df20['director_name']+' '+new_df20['genres']

In [65]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,DemiÃ¡n Bichir,John Cho,Horror Mystery,the grudge,Andrea Riseborough DemiÃ¡n Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Drama Thriller Crime,inherit the viper,Josh Hartnett Margarita Levieva Chandler Riggs...
4,Andrew Desmond,Freya Tingley,Simon Abkarian,Rutger Hauer,Horror Thriller Mystery,the sonata,Freya Tingley Simon Abkarian Rutger Hauer Andr...
...,...,...,...,...,...,...,...
159,Denis Villeneuve,TimothÃ©e Chalamet,Rebecca Ferguson,Oscar Isaac,Action Science Fiction Adventure,dune,TimothÃ©e Chalamet Rebecca Ferguson Oscar Isaac...
160,Steven Spielberg,Ansel Elgort,Rachel Zegler,Ariana DeBose,Crime Drama Romance,west side story,Ansel Elgort Rachel Zegler Ariana DeBose Steve...
161,Craig Brewer,Eddie Murphy,Jermaine Fowler,Arsenio Hall,Comedy,coming 2 america,Eddie Murphy Jermaine Fowler Arsenio Hall Crai...
162,Joel Crawford,Nicolas Cage,Emma Stone,Ryan Reynolds,Action Adventure Animation Comedy Family Fantasy,the croods 2,Nicolas Cage Emma Stone Ryan Reynolds Joel Cra...
163,Paul Greengrass,Tom Hanks,Helena Zengel,Neil Sandilands,Drama Western,news of the world,Tom Hanks Helena Zengel Neil Sandilands Paul G...

In [66]:
old_df=pd.read_csv('C:/Users/pallaw/Desktop/ML&Deep_Learning/final_data.csv')

In [67]:
old_df.columns

Index(['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name',
       'genres', 'movie_title', 'comb'],
      dtype='object')

In [68]:
new_df20.columns

Index(['director_name', 'actor_1_name', 'actor_2_name', 'actor_3_name',
       'genres', 'movie_title', 'comb'],
      dtype='object')

In [69]:
final_df=old_df.append(new_df20,ignore_index=True)

In [70]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Wes Studi,Wes Studi,Action|Adventure|Fantasy|Sci-Fi,avatar,CCH Pounder Wes Studi Wes Studi James Cameron ...
1,Gore Verbinski,Johnny Depp,Jack Davenport,Jack Davenport,Action|Adventure|Fantasy,pirates of the caribbean: at world's end,Johnny Depp Jack Davenport Jack Davenport Gore...
2,Sam Mendes,Christoph Waltz,Stephanie Sigman,Stephanie Sigman,Action|Adventure|Thriller,spectre,Christoph Waltz Stephanie Sigman Stephanie Sig...
3,Christopher Nolan,Tom Hardy,Joseph Gordon-Levitt,Joseph Gordon-Levitt,Action|Thriller,the dark knight rises,Tom Hardy Joseph Gordon-Levitt Joseph Gordon-L...
4,Doug Walker,Doug Walker,unknown,NaN,Documentary,star wars: episode vii - the force awakensÂ ...,NaN
...,...,...,...,...,...,...,...
6032,Denis Villeneuve,TimothÃ©e Chalamet,Rebecca Ferguson,Oscar Isaac,Action Science Fiction Adventure,dune,TimothÃ©e Chalamet Rebecca Ferguson Oscar Isaac...
6033,Steven Spielberg,Ansel Elgort,Rachel Zegler,Ariana DeBose,Crime Drama Romance,west side story,Ansel Elgort Rachel Zegler Ariana DeBose Steve...
6034,Craig Brewer,Eddie Murphy,Jermaine Fowler,Arsenio Hall,Comedy,coming 2 america,Eddie Murphy Jermaine Fowler Arsenio Hall Crai...
6035,Joel Crawford,Nicolas Cage,Emma Stone,Ryan Reynolds,Action Adventure Animation Comedy Family Fantasy,the croods 2,Nicolas Cage Emma Stone Ryan Reynolds Joel Cra...
6036,Paul Greengrass,Tom Hanks,Helena Zengel,Neil Sandilands,Drama Western,news of the world,Tom Hanks Helena Zengel Neil Sandilands Paul G...

In [71]:
final_df.to_csv('C:/Users/pallaw/Desktop/ML&Deep_Learning/main_data.csv',index=False)